# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastgws',
                'doc_host': 'https://ncoop57.github.io',
                'git_url': 'https://github.com/ncoop57/fastgws',
                'lib_path': 'fastgws'},
  'syms': { 'fastgws.auth': {},
            'fastgws.core': { 'fastgws.core.GWSApi': ('core.html#gwsapi', 'fastgws/core.py'),
                              'fastgws.core.GWSApi.__init__': ('core.html#gwsapi.__init__', 'fastgws/core.py'),
                              'fastgws.core.GWSApi._get_doc': ('core.html#gwsapi._get_doc', 'fastgws/core.py'),
                              'fastgws.core.GWSObject': ('core.html#gwsobject', 'fastgws/core.py'),
                              'fastgws.core.GWSObject.__repr__': ('core.html#gwsobject.__repr__', 'fastgws/core.py'),
                              'fastgws.core.GWSTransport': ('core.html#gwstransport', 'fastgws/core.py'),
                              'fastgws.core.GWSTransport.__init__': ('core.html#gwstransport.__init__', 'fastgws/core.py'),
                              'fastgws.core.GWSTransport.request': ('core.html#gwstransport.request', 'fastgws/core.py'),
                              'fastgws.core.g2obj': ('core.html#g2obj', 'fastgws/core.py'),
                              'fastgws.core.gclasses': ('core.html#gclasses', 'fastgws/core.py')}}}
