"""Workspace user and license administration through Google APIs.

`WorkspaceAdmin` keeps the Admin Directory and Enterprise License Manager clients together. User creation, licensing, suspension, and deletion remain separate operations, so callers choose the lifecycle they need.

Docs: https://answerdotai.github.io/fastgws/admin.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_admin.ipynb.

# %% auto #0
__all__ = ['WorkspaceAdmin']

# %% ../nbs/01_admin.ipynb #b8709a73
from fastcore.utils import *
from .core import GWSApi

# %% ../nbs/01_admin.ipynb #00a7bf29
class WorkspaceAdmin:
    "High-level Workspace user and license administration"
    def __init__(self, creds):
        self.directory = GWSApi('admin', version='directory_v1', creds=creds)
        self.licensing = GWSApi('licensing', version='v1', creds=creds)

    async def create_user(
        self,
        primary_email:str, # New user's primary email address
        given_name:str, # Given name
        family_name:str, # Family name
        password:str, # Initial password
        org_unit_path:str='/', # Parent organizational unit
        change_password_at_next_login:bool=False, # Force a password change on first login?
        **kwargs
    ):
        "Create a Workspace user"
        return await self.directory.users.insert(primary_email=primary_email,
            name=dict(given_name=given_name, family_name=family_name), password=password,
            org_unit_path=org_unit_path, change_password_at_next_login=change_password_at_next_login, **kwargs)

# %% ../nbs/01_admin.ipynb #7c43dab8
@patch
async def assign_license(
    self:WorkspaceAdmin,
    user_id:str, # User's primary email address
    sku_id:str, # Workspace product SKU
    product_id:str='Google-Apps', # Workspace product ID
):
    "Assign a product licence to a user"
    return await self.licensing.license_assignments.insert(product_id=product_id, sku_id=sku_id, user_id=user_id)


# %% ../nbs/01_admin.ipynb #e129658a
@patch
async def remove_license(
    self:WorkspaceAdmin,
    user_id:str, # User's primary email address
    sku_id:str, # Workspace product SKU
    product_id:str='Google-Apps', # Workspace product ID
):
    "Remove a product licence from a user"
    return await self.licensing.license_assignments.delete(product_id=product_id, sku_id=sku_id, user_id=user_id)


# %% ../nbs/01_admin.ipynb #d4537263
@patch
async def suspend_user(
    self:WorkspaceAdmin,
    user_key:str, # Primary email, alias, or immutable user ID
    suspended:bool=True, # Suspend rather than restore the user?
):
    "Set a user's suspension state"
    return await self.directory.users.update(user_key=user_key, suspended=suspended)


# %% ../nbs/01_admin.ipynb #d31e77d9
@patch
async def delete_user(
    self:WorkspaceAdmin,
    user_key:str, # Primary email, alias, or immutable user ID
):
    "Delete a Workspace user"
    return await self.directory.users.delete(user_key=user_key)

