"""Async Google Workspace clients built from Google's Discovery API.

Docs: https://answerdotai.github.io/fastgws/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['GWSObject', 'gclasses', 'g2obj', 'GWSTransport', 'request_bytes', 'response_from_bytes', 'GWSOpFunc', 'GWSApi']

# %% ../nbs/00_core.ipynb #1a375d85
from collections.abc import Sized
from datetime import timezone
from email.message import EmailMessage
from email.parser import BytesParser
from email.policy import default as email_policy
from email.utils import parsedate_to_datetime
from urllib.parse import urljoin
from uuid import uuid4

from fastcore.utils import *
from .auth import *
from fasttransport.errors import APIError
from fastspec.spec import SpecParser
from fastspec.oapi import AsyncTransport, OpFunc
from fastcore.apisurface import mk_groups
from fastcore.meta import delegates

import asyncio, h11, httpx, httpx2, math, random, time

# %% ../nbs/00_core.ipynb #bcf1c22a
class GWSObject(AttrDict):
    def __repr__(self):
        keys = 'id name title summary emailAddress threadId documentId spreadsheetId sheetId mimeType kind'.split()
        bits = [f"{k}={self[k]!r}" for k in keys if k in self]
        bits += [f"{k}={len(v)}" for k,v in self.items()
            if isinstance(v, Sized) and not isinstance(v, (str, bytes)) and k not in keys]
        return f"{type(self).__name__}({', '.join(bits)})"

def gclasses(doc):
    res = {}
    for n,s in doc.get('schemas', {}).items():
        kind = nested_idx(s, 'properties', 'kind', 'default')
        if kind: res[kind] = type(n, (GWSObject,), {})
    return res

def g2obj(x, gcls):
    if isinstance(x, list): return L(x).map(lambda o: g2obj(o, gcls))
    if not isinstance(x, dict): return x
    cls = gcls.get(x.get('kind'), GWSObject)
    return cls({k:g2obj(v, gcls) for k,v in x.items()})

# %% ../nbs/00_core.ipynb #e6dae508
_rate_reasons = {'ratelimitexceeded', 'userratelimitexceeded', 'rate_limit_exceeded', 'user_rate_limit_exceeded'}

def _error_items(err, key):
    raw = err.raw
    error = raw.get('error') if isinstance(raw, dict) else None
    items = error.get(key) if isinstance(error, dict) else None
    return [o for o in items if isinstance(o, dict)] if isinstance(items, list) else []

def _error_details(err, name):
    return [o for o in _error_items(err, 'details') if o.get('@type') == f'type.googleapis.com/google.rpc.{name}']

def _retryable(err):
    reasons = [o.get('reason') for o in _error_items(err, 'errors') + _error_details(err, 'ErrorInfo')]
    return err.retryable or any(isinstance(r, str) and r.casefold() in _rate_reasons for r in reasons)

# %% ../nbs/00_core.ipynb #1d1186e6
def _number(value):
    try:
        res = float(value)
        if math.isfinite(res): return res
    except (TypeError, ValueError, OverflowError): pass

def _retry_after(err, now):
    if err.response is None: return
    value = err.response.headers.get('retry-after')
    if not value: return
    seconds = _number(value)
    if seconds is not None: return seconds if seconds >= 0 else None
    try:
        when = parsedate_to_datetime(value)
        if when.tzinfo is None: when = when.replace(tzinfo=timezone.utc)
        return max(0, when.timestamp() - now)
    except (TypeError, ValueError, OverflowError): return

# %% ../nbs/00_core.ipynb #052ea42e
_period_secs = dict(s=1, min=60, h=3600, d=86400)

def _retry_info(err):
    waits = []
    for info in _error_details(err, 'RetryInfo'):
        value = info.get('retryDelay')
        m = re.fullmatch(r'(\d+(?:\.\d{1,9})?)s', value) if isinstance(value, str) else None
        wait = _number(m[1]) if m else None
        if wait is not None: waits.append(wait)
    return max(waits, default=None)

def _quota_wait(err, now):
    waits = []
    for info in _error_details(err, 'ErrorInfo'):
        meta = info.get('metadata')
        if not isinstance(meta, dict): continue
        unit = meta.get('quota_unit')
        m = re.fullmatch(r'[1-9]\d*/(\d*)(s|min|h|d)(?:/.*)?', unit) if isinstance(unit, str) else None
        period = _number(m[1] or 1) if m else None
        start = _number(meta.get('window_start_time'))
        if not period or start is None: continue
        end = _number(start + period * _period_secs[m[2]])
        if end is not None: waits.append(max(0, end - now) + 1)
    return max(waits, default=None)

# %% ../nbs/00_core.ipynb #15c829f6
def _retry_delay(err, attempt, base, max_backoff, max_wait=300.0, now=None):
    now = time.time() if now is None else now
    delay = _retry_after(err, now)
    if delay is None: delay = _retry_info(err)
    if delay is None: delay = _quota_wait(err, now)
    if delay is None: delay = min(max_backoff, base*2**attempt) + random.uniform(0, base)
    return delay if delay <= max_wait else None


# %% ../nbs/00_core.ipynb #f45206ac
def _retry_action(err, attempt, n_retries, can_refresh, base=1.0, max_backoff=64.0, max_wait=300.0):
    if attempt == n_retries-1: return 'stop',None
    if err.status_code == 401 and can_refresh: return 'refresh',None
    if not _retryable(err): return 'stop',None
    delay = _retry_delay(err, attempt, base, max_backoff, max_wait)
    return ('stop', None) if delay is None else ('wait', delay)

# %% ../nbs/00_core.ipynb #ceb0c83c
class GWSTransport(AsyncTransport):
    def __init__(self, *args, gcls=None, creds=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.gcls,self.creds = gcls or {},creds

    def _request_headers(self, headers=None, *, files=None):
        if self.creds: self.base_headers |= auth_headers(self.creds)
        return super()._request_headers(headers, files=files)

# %% ../nbs/00_core.ipynb #b9ee6256
@patch
@delegates(AsyncTransport.request)
async def request(
    self:GWSTransport, *args, raw=False,
    n_retries=5, # Maximum attempts, including the initial request
    base=1.0, # Initial exponential backoff and jitter range, in seconds
    max_backoff=64.0, # Maximum exponential component, in seconds
    max_wait=300.0, # Maximum individual retry wait, in seconds
    **kwargs
):
    if n_retries < 1: raise ValueError('n_retries must be at least 1')
    if not math.isfinite(max_wait) or max_wait < 0: raise ValueError('max_wait must be finite and non-negative')
    refreshed = False
    for attempt in range(n_retries):
        try:
            if self.creds and not self.creds.valid: await refresh_creds(self.creds)
            res = await super(GWSTransport, self).request(*args, raw=raw, **kwargs)
            return res if raw else g2obj(res, self.gcls)
        except (httpx2.HTTPStatusError, httpx2.RequestError) as e:
            can_refresh = self.creds and not refreshed
            action,delay = _retry_action(e.api_error(), attempt, n_retries, can_refresh, base, max_backoff, max_wait)
            if action == 'stop': raise
            if action == 'refresh':
                refreshed = True
                await refresh_creds(self.creds)
            else: await asyncio.sleep(delay)

# %% ../nbs/00_core.ipynb #1bb4f544
def request_bytes(request):
    "Serialize a buffered `httpx2.Request` as HTTP/1.1"
    conn = h11.Connection(h11.CLIENT)
    head = h11.Request(method=request.method, target=request.url.raw_path, headers=request.headers.raw)
    return conn.send(head) + conn.send(h11.Data(data=request.content)) + conn.send(h11.EndOfMessage())

def response_from_bytes(data, request):
    "Parse one complete HTTP response for `request`; raise `h11.RemoteProtocolError` for invalid framing"
    conn = h11.Connection(h11.CLIENT)
    conn.send(h11.Request(method=request.method, target=request.url.raw_path, headers=[(b'Host', request.url.netloc)]))
    conn.send(h11.EndOfMessage())
    conn.receive_data(data)
    conn.receive_data(b'')
    response,body = None,[]
    while True:
        event = conn.next_event()
        if isinstance(event, h11.Response): response = event
        elif isinstance(event, h11.Data): body.append(event.data)
        elif isinstance(event, h11.EndOfMessage): break
        elif isinstance(event, h11.InformationalResponse) and event.status_code != 101: continue
        else: raise h11.RemoteProtocolError('Incomplete HTTP response')
    if response is None or conn.trailing_data[0]: raise h11.RemoteProtocolError('Expected one complete HTTP response')
    return httpx2.Response(response.status_code, headers=response.headers, content=b''.join(body), request=request,
        extensions={'http_version':b'HTTP/' + response.http_version, 'reason_phrase':response.reason})

# %% ../nbs/00_core.ipynb #18bfc7d0
class GWSOpFunc(OpFunc):
    def _raise_with_context(self, exc, *, endpoint=''):
        if isinstance(exc, (httpx2.HTTPStatusError, httpx2.RequestError)):
            err = exc.api_error(endpoint=endpoint)
            err.retryable = _retryable(err)
            raise err from exc
        raise exc

    def _batch_call(self, call):
        if not isinstance(call, dict): raise TypeError('batch calls must be dictionaries of operation arguments')
        stream,url,headers,query,route,kw = self._prep((), dict(call))
        if stream: raise TypeError('batch calls cannot stream')
        unsupported = set(kw)-{'body'}
        if unsupported: raise TypeError(f'batch calls do not support {", ".join(sorted(unsupported))}')
        return httpx2.Request(self.verb, url, headers=headers, params=query, json=kw.get('body'))

    def _batch_content(self, calls, boundary):
        requests = [self._batch_call(call) for call in calls]
        msg = EmailMessage(policy=email_policy.clone(linesep='\r\n'))
        msg.make_mixed(boundary=boundary)
        for i,request in enumerate(requests):
            part = EmailMessage()
            part.set_content(request_bytes(request), maintype='application', subtype='http', cte='binary')
            part['Content-ID'] = f'<{i}>'
            msg.attach(part)
        return msg.as_bytes().partition(b'\r\n\r\n')[2],requests


# %% ../nbs/00_core.ipynb #c73cb296
@patch
def _batch_results(self:GWSOpFunc, response, requests):
    ctype = response.headers.get('content-type')
    if not ctype: raise ValueError('Google batch response has no Content-Type')
    prefix = f'Content-Type: {ctype}\r\n\r\n'.encode()
    msg = BytesParser(policy=email_policy.clone(raise_on_defect=True)).parsebytes(prefix + response.content)
    if msg.get_content_type() != 'multipart/mixed': raise ValueError('Google batch response must be multipart/mixed')
    parts = list(msg.iter_parts())
    if len(parts) != len(requests): raise ValueError(f'Google batch returned {len(parts)} parts for {len(requests)} calls')
    results = []
    for part,request in zip(parts, requests):
        if part.get_content_type() != 'application/http': raise ValueError('Google batch parts must be application/http')
        inner = response_from_bytes(part.get_payload(decode=True), request)
        try: inner.raise_for_status()
        except httpx2.HTTPStatusError as e:
            err = e.api_error(endpoint=f'{request.method} {request.url.path}')
            err.retryable = _retryable(err)
            results.append(err)
        else: results.append(g2obj(self.client._decode(inner), self.client.gcls))
    return results

# %% ../nbs/00_core.ipynb #275daa1e
@patch
async def _batch_once(self:GWSOpFunc, calls, n_retries, base, max_backoff, max_wait):
    boundary = f'fastgws_{uuid4().hex}'
    content,requests = self._batch_content(calls, boundary)
    headers = {'Content-Type':f'multipart/mixed; boundary={boundary}'}
    try:
        response = await self.client.request('POST', self.batch_url, headers=headers, content=content, raw=True,
            n_retries=n_retries, base=base, max_backoff=max_backoff, max_wait=max_wait)
    except Exception as e: self._raise_with_context(e, endpoint=self.batch_url)
    return self._batch_results(response, requests)

# %% ../nbs/00_core.ipynb #63a9b287
@patch
async def _batch_chunk(self:GWSOpFunc, calls, n_retries, base, max_backoff, max_wait):
    results,pending,refreshed = [None]*len(calls),dict(enumerate(calls)),False
    for attempt in range(n_retries):
        indexes = list(pending)
        values = await self._batch_once([pending[i] for i in indexes], n_retries, base, max_backoff, max_wait)
        retry,refresh,waits = {},False,[]
        for i,value in zip(indexes, values):
            if not isinstance(value, APIError):
                results[i] = value
                continue
            action,delay = _retry_action(value, attempt, n_retries, self.client.creds and not refreshed, base, max_backoff, max_wait)
            if action == 'stop': results[i] = value
            else:
                retry[i] = pending[i]
                if action == 'refresh': refresh = True
                else: waits.append(delay)
        if not retry: break
        if refresh:
            refreshed = True
            await refresh_creds(self.client.creds)
        if waits: await asyncio.sleep(max(waits))
        pending = retry
    return results


# %% ../nbs/00_core.ipynb #2c842525
@patch
async def batch(
    self:GWSOpFunc,
    calls, # Dictionaries of operation arguments, in result order
    chunk=50, # Calls per batch request, at most 100
    return_exceptions=False, # Return per-call APIError values instead of raising
    n_retries=5, # Maximum attempts for each batch request and failed part
    base=1.0, # Initial exponential backoff and jitter range, in seconds
    max_backoff=64.0, # Maximum exponential component, in seconds
    max_wait=300.0 # Maximum individual retry wait, in seconds
):
    "Run dictionaries of arguments for this operation through Google's discovery-advertised HTTP batch endpoint"
    if not self.batch_url: raise ValueError('This Google service does not advertise a batch endpoint')
    if not 1 <= chunk <= 100: raise ValueError('chunk must be between 1 and 100')
    if n_retries < 1: raise ValueError('n_retries must be at least 1')
    if not math.isfinite(max_wait) or max_wait < 0: raise ValueError('max_wait must be finite and non-negative')
    calls = list(calls)
    results = []
    for i in range(0, len(calls), chunk): results.extend(await self._batch_chunk(calls[i:i+chunk], n_retries, base, max_backoff, max_wait))
    if not return_exceptions:
        error = first(x for x in results if isinstance(x, APIError))
        if error: raise error
    return results


# %% ../nbs/00_core.ipynb #6e181426
def _api_headers(creds=None, token=None, api_key=None, headers=None):
    hdrs = headers or {}
    if creds or token: hdrs = {**auth_headers(creds, token), **hdrs}
    if api_key is None and not (creds or token): api_key = os.getenv('GOOGLE_API_KEY', os.getenv('GWS_API_KEY'))
    if api_key: hdrs = {'X-Goog-Api-Key': api_key, **hdrs}
    return hdrs

# %% ../nbs/00_core.ipynb #151ae5d3
class GWSApi:
    service = None

    def __init__(self, service=None, version=None, token=None, creds=None,
        api_key=None, headers=None, timeout=60.0, doc=None):
        service = ifnone(service, self.service)
        if service is None: raise ValueError('`service` is required')
        self.service,self.version = service,version
        self.doc = doc or self._get_doc(service, version)
        self.spec = SpecParser.from_discovery(self.doc)
        self.gcls = gclasses(self.doc)

        hdrs = {'Accept-Encoding':'gzip', 'User-Agent':'fastgws (gzip)', **(headers or {})}
        hdrs = _api_headers(creds, token, api_key, hdrs)

        root,batch_path = self.doc.get('rootUrl'),self.doc.get('batchPath')
        batch_url = urljoin(root.rstrip('/')+'/', batch_path) if root and batch_path else None
        self.transport = GWSTransport(timeout=timeout, base_headers=hdrs, gcls=self.gcls, creds=creds)
        self.ops = [GWSOpFunc(o, self.transport, self.spec.base_url, noop) for o in self.spec.ops]
        for op in self.ops: op.batch_url = batch_url
        self.func_dict = {f"{o.path}:{o.verb.upper()}": o for o in self.ops}
        self.groups = mk_groups(self.ops)
        for k,v in self.groups.items(): setattr(self, k, v)

    def _get_doc(self, service, version=None):
        if version: url = f'https://www.googleapis.com/discovery/v1/apis/{service}/{version}/rest'
        else:
            apis = httpx.get('https://discovery.googleapis.com/discovery/v1/apis').json()['items']
            api = first(a for a in apis if a['name'] == service and a.get('preferred'))
            url = api['discoveryRestUrl']
            self.version = api['version']
        return httpx.get(url).json()


# %% ../nbs/00_core.ipynb #25a21f0f
@patch(cls_method=True)
async def from_discovery_url(cls:GWSApi, url, service=None, version=None, token=None, creds=None,
    api_key=None, headers=None, quota_project=None, timeout=60.0):
    "Create a client from a discovery document fetched from `url`"
    headers = headers or {}
    quota_project = quota_project or getattr(creds, 'quota_project_id', None)
    if quota_project: headers = {'X-Goog-User-Project': quota_project, **headers}
    if creds and not creds.valid: await refresh_creds(creds)
    hdrs = _api_headers(creds, token, api_key, headers)
    async with httpx.AsyncClient(timeout=timeout) as client:
        response = await client.get(url, headers=hdrs)
        response.raise_for_status()
    doc = response.json()
    service = service or cls.service or doc.get('name')
    version = version or doc.get('version')
    return cls(service=service, version=version, token=token, creds=creds,
        api_key=api_key, headers=headers, timeout=timeout, doc=doc)


# %% ../nbs/00_core.ipynb #b931d142
@patch
async def pages(self:GWSOpFunc, *args, **kwargs):
    "Yield every page from a Google list operation"
    while True:
        page = await self(*args, **kwargs)
        yield page
        token = page.get('nextPageToken')
        if not token: return
        kwargs['page_token'] = token

